## Python Implementation of Dijkstra's Algorithm
- For finding the shortest path from the source vertex
-  to all other vertices in the graph
- Shortest path can be presented in multiple contexts:
        - distance, time, cost etc

In [2]:
import numpy as np

In [4]:
"""
INPUTS
W - A weight matrix; a square matrix
i - The number of source node

OUTPUTS
shortestDistances - shortest distances from the source to each Vertex
previousVertices - the previous vertex to the destination in shortest path
    from the source to a destination
"""
def Dijkstra(W, i):
    # find the number of vertices
    n = W.shape[0]

    # initialize the shortest distances to infinity
    shortestDistances = np.array([np.inf] * n)

    previousVertices = np.array([np.inf] * n)

    # initialize the unvisited vertex set to be full
    unvisited = np.array([1] * n)

    # mark the source as visited
    unvisited[i-1] = 0

    # initialize distance from the source to the source as 0
    shortestDistances[i - 1] = 0

    # create loop to find the nearest unvisited vertex
    # loop for iteration per vertex until the unvisited set is empty
    for _ in range(n):
        # find the distances to all unvisited adjacent vertices
        # and set others to 0
        distances = shortestDistances * unvisited

        # find the index of the nearest unvisited vertex
        # distance > 0
        x = np.argmin(np.ma.masked_where(distances == 0, distances))

        unvisited[x] = 0

        # Iterating through the vertices
        for v in range(n):

            oldDistance = shortestDistances[v]
            newDistance = shortestDistances[x] + W[v,x]
            adj = W[v,x] > 0
            unVis = unvisited[v]

            # if v and x are connected, v has not been visited

            if adj and unVis and oldDistance > newDistance:
                shortestDistances[v] = shortestDistances[x] + W[v,x]
                previousVertices[v] = x
        print(np.array([np.arange(n) + 1, shortestDistances, previousVertices + 1]).T)
        return shortestDistances, previousVertices

## Test Shortest Paths with Dijkstra's Algorithm

In [5]:
# Create a weight matrix for the network
w1 = np.array([[0, 4, 1, 0, 2, 0],
               [4, 0, 2, 1, 0, 1],
               [1, 2, 0, 1, 1, 0],
               [0, 1, 1, 0, 2, 0],
               [2, 0, 1, 2, 0, 0],
               [0, 1, 0, 0, 0, 0]])

Dijkstra(w1, 1)

[[ 1.  0. inf]
 [ 2.  4.  1.]
 [ 3.  1.  1.]
 [ 4. inf inf]
 [ 5.  2.  1.]
 [ 6. inf inf]]


(array([ 0.,  4.,  1., inf,  2., inf]), array([inf,  0.,  0., inf,  0., inf]))